export default {
  pages: {
    product_planning: 'all',
    build_plan_eco: 'all',
    history_eco: 'all',
    create_eco: 'all',
    request_for_purchase: 'add_part',
    summary_part_status: 'all',
    quotation_summary: 'all',
    part_detail: 'all',
    release_po: 'Release_PO',
    set_approval_limit: 'all',
    // rfq_approval: "Approve_Request_for_Part",
    rfq_approval: 'Approve_RFQ',
    po_approval: 'Approve_PO',
    dashboard: 'Buyer_dashboard',
    edit_user: 'Edit_User',
    add_user: 'Buyer_User_addition',
    non_disclosure: 'all',
    part_detail: 'Edit_part_details',

    purchasing_of_summary: 'all',
    supplier_criteria_setting: 'all',
    purchase_category: 'Create_Purchasing_Category',
    create_indirect_purchase_request: 'Create_Indirect_Purchase_Request',
    edit_indirect_purchase_request: 'Edit_Indirect_Purchase_Request',
    set_approval_limit: 'set_approval_limit',
    geographical: 'all'
  },
  action: {
    review_quotations: 'Review_Quotations',
    part_detail: 'Edit_part_details',
    edit: 'Forward_parts_to_suppliers',
    delete: 'all',
    view: 'all'
  },
  footer_title: {
    product_planning: 'product_planning',
    build_plan_eco: 'build_plan_eco',
    history_eco: 'history_eco',
    create_eco: 'create_eco',
    request_for_purchase: 'request_for_purchase',
    summary_part_status: 'summary_part_status',
    quotation_summary: 'quotation_summary',
    part_detail: 'part_detail',
    release_po: 'release_po',
    set_approval_limit: 'set_approval_limit',
    rfq_approval: 'approve_rfq',
    // rfq_approval: 'Approve_Request_for_Part',
    po_approval: 'approve_po',
    dashboard: 'buyer_dashboard',
    edit_user: 'edit_user',
    add_user: 'add_user',
    non_disclosure: 'non_disclosure',
    // edit_part_detail: 'edit_part_details',
    product_plannning: 'product_plannning',
    purchasing_of_summary: 'purchasing_of_summary',
    supplier_criteria_setting: 'supplier_criteria_setting',
    review_summary: 'review_summary',
    release: 'release',
    buyer_ppap: 'buyer_ppap',
    audit: 'audit',
    buyer_criteria: 'buyer_criteria',
    tree: 'tree',
    review_supplier: 'review_supplier',
    existing: 'existing',
    value_analyst: 'value_analyst',
    user_profile: 'value_analyst',
    review_po_approval: 'review_po_approval'
  },
  roles: {
    admin: 'admin',
    buyer: 'buyer',
    designer: 'designer',
    value_analyst: 'value_analyst',
    purchase_manager: 'purchase_manager',
    designer_approver: 'designer_approver',
    product_cost_manager: 'product_cost_manager',
    product_cost_approver: 'product_cost_approver',
    head_product_development: 'head_product_development',
    manufacturing_engineer: 'manufacturing_engineer'
  }
};
